// Replace these two values with your Supabase Project URL and Publishable Key.
const SUPABASE_URL="YOUR_SUPABASE_URL";
const SUPABASE_PUBLISHABLE_KEY="YOUR_SUPABASE_PUBLISHABLE_KEY";
let supabaseClient=null,transactions=[],savingsGoal=10000;const budgetLimit=10000;
const categoryColors={Food:'#f06292',Transport:'#42a5e8',Entertainment:'#ffd05a',Bills:'#4caf50',Health:'#9c27b0',Shopping:'#ff9800',Other:'#90a4ae'};const money=v=>'₹'+Number(v||0).toFixed(2);
function configured(){return SUPABASE_URL!=='YOUR_SUPABASE_URL'&&SUPABASE_PUBLISHABLE_KEY!=='YOUR_SUPABASE_PUBLISHABLE_KEY'}function status(m,t=''){const e=document.getElementById('dbStatus');e.textContent=m;e.className='db-status '+t}
async function loadTransactions(){if(!configured()){status('Supabase not configured — add credentials in script.js.','error');render();return}const{data,error}=await supabaseClient.from('transactions').select('*').order('created_at',{ascending:false});if(error){console.error(error);status('Database error: '+error.message,'error');render();return}transactions=data||[];status('Connected to Supabase','connected');render()}
async function addTransaction(t){if(!configured()){alert('Add your Supabase URL and publishable key in script.js first.');return false}const{data,error}=await supabaseClient.from('transactions').insert(t).select().single();if(error){console.error(error);alert('Could not save transaction:\n'+error.message);return false}transactions.unshift(data);return true}
async function loadSavingsGoal(){if(!configured())return;const{data,error}=await supabaseClient.from('savings_goals').select('*').order('created_at',{ascending:false}).limit(1);if(!error&&data&&data.length)savingsGoal=Number(data[0].goal_amount)}
async function saveSavingsGoal(value){if(!configured()){alert('Configure Supabase first.');return}const{error:de}=await supabaseClient.from('savings_goals').delete().neq('id',0);if(de){alert('Could not update savings goal:\n'+de.message);return}const{error:ie}=await supabaseClient.from('savings_goals').insert({goal_amount:value});if(ie){alert('Could not save savings goal:\n'+ie.message);return}savingsGoal=value;render()}
function render(){const income=transactions.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount),0),expenses=transactions.filter(t=>t.type==='expense'),expense=expenses.reduce((s,t)=>s+Number(t.amount),0),balance=income-expense,prediction=expenses.length?expense/expenses.length:0;document.getElementById('incomeTotal').textContent=money(income);document.getElementById('expenseTotal').textContent=money(expense);document.getElementById('balanceTotal').textContent=money(balance);document.getElementById('predictionTotal').textContent=money(prediction);document.getElementById('reportIncome').textContent=money(income);document.getElementById('reportExpense').textContent=money(expense);document.getElementById('reportSavings').textContent=money(balance);document.getElementById('goal').value=savingsGoal||'';const progress=savingsGoal>0?Math.max(0,Math.min(100,balance/savingsGoal*100)):0;document.getElementById('progressText').textContent=progress.toFixed(2)+'%';document.getElementById('progressBar').style.width=progress+'%';const a=document.getElementById('budgetAlert');if(expense>budgetLimit){a.className='alert warn';a.textContent='⚠ Spending has exceeded the budget'}else{a.className='alert ok';a.textContent='☑ Spending is within budget'}const rows=document.getElementById('transactionRows');rows.innerHTML='';transactions.forEach(t=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(t.description)}</td><td>${esc(t.category)}</td><td>${esc(t.type)}</td><td>${money(t.amount)}</td>`;rows.appendChild(tr)});renderChart(expenses)}
function renderChart(expenses){const totals={};expenses.forEach(t=>totals[t.category]=(totals[t.category]||0)+Number(t.amount));const total=Object.values(totals).reduce((a,b)=>a+b,0),categories=Object.keys(totals);document.getElementById('legend').innerHTML=categories.map(c=>`<span class="legend-item"><span class="dot" style="background:${categoryColors[c]||categoryColors.Other}"></span>${esc(c)}</span>`).join('');const pie=document.getElementById('pieChart');if(!total){pie.style.background='#e0e0e0';return}let angle=0,stops=[];categories.forEach(c=>{const start=angle;angle+=totals[c]/total*360;stops.push(`${categoryColors[c]||categoryColors.Other} ${start}deg ${angle}deg`)});pie.style.background=`conic-gradient(${stops.join(',')})`}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
document.getElementById('transactionForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button'),description=document.getElementById('description').value.trim(),amount=Number(document.getElementById('amount').value),type=document.getElementById('type').value,category=document.getElementById('category').value;if(!description||!amount||amount<=0)return;b.disabled=true;b.textContent='Saving...';const ok=await addTransaction({description,amount,type,category});b.disabled=false;b.textContent='Add Transaction';if(!ok)return;render();e.target.reset();document.getElementById('type').value='expense';document.getElementById('category').value='Other'});
document.getElementById('goalBtn').addEventListener('click',async()=>{const value=Number(document.getElementById('goal').value);if(value>0)await saveSavingsGoal(value)});document.getElementById('exportBtn').addEventListener('click',()=>window.print());
async function initialize(){if(configured()){supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);await loadSavingsGoal()}await loadTransactions()}initialize();
