create table if not exists public.transactions(id bigint generated by default as identity primary key,description text not null,amount numeric(12,2) not null check(amount>0),type text not null check(type in ('income','expense')),category text not null,created_at timestamp with time zone default now());
create table if not exists public.savings_goals(id bigint generated by default as identity primary key,goal_amount numeric(12,2) not null check(goal_amount>0),created_at timestamp with time zone default now());
alter table public.transactions enable row level security;alter table public.savings_goals enable row level security;
create policy "Allow public read transactions" on public.transactions for select to anon using(true);
create policy "Allow public insert transactions" on public.transactions for insert to anon with check(true);
create policy "Allow public read savings goals" on public.savings_goals for select to anon using(true);
create policy "Allow public insert savings goals" on public.savings_goals for insert to anon with check(true);
create policy "Allow public delete savings goals" on public.savings_goals for delete to anon using(true);
-- Optional sample data matching the original demo.
insert into public.transactions(description,amount,type,category) values('Monthly Salary',80000,'income','Salary'),('Dinner',140,'expense','Food'),('Travel to Chennai',1000,'expense','Transport'),('Netflix Subscription',899,'expense','Entertainment'),('Electricity Bill',506,'expense','Bills'),('Water Bill',403,'expense','Bills'),('Gas bill',800,'expense','Bills'),('Dental Checkup',3000,'expense','Health'),('Groceries',800,'expense','Shopping');
insert into public.savings_goals(goal_amount) values(10000);
